module.exports = [
    {
        model : 'employee',
        data: [
            {firstName: "Cason", lastName: "Villarreal", emailId : "Cason.Villarreal@email.com"},
            {firstName: "Elisa", lastName: "Dodson", emailId : "Elisa.Dodson@email.com"},
            {firstName: "Lizbeth", lastName: "Wiggins", emailId : "Lizbeth.Wiggins@email.com"},
            {firstName: "Marilyn", lastName: "Morris", emailId : "Marilyn.Morris@email.com"},
            {firstName: "Ada", lastName: "Neal", emailId : "Ada.Neal@email.com"},
            {firstName: "Denisse", lastName: "Krueger", emailId : "Denisse.Krueger@email.com"},
            {firstName: "Baylee", lastName: "Hopkins", emailId : "Baylee.Hopkins@email.com"},
            {firstName: "Nathalia", lastName: "Rodgers", emailId : "Nathalia.Rodgers@email.com"},
            {firstName: "Gauge", lastName: "Bautista", emailId : "Gauge.Bautista@email.com"},
            {firstName: "Porter", lastName: "Hurst", emailId : "Porter.Hurst@email.com"},
            {firstName: "Kaley", lastName: "Smith", emailId : "Kaley.Smith@email.com"},
            {firstName: "Pedro", lastName: "Graham", emailId : "Pedro.Graham@email.com"},
            {firstName: "Craig", lastName: "Webb", emailId : "Craig.Webb@email.com"},
            {firstName: "Noelle", lastName: "Duffy", emailId : "Noelle.Duffy@email.com"},
            {firstName: "Lucille", lastName: "Kane", emailId : "Lucille.Kane@email.com"},
            {firstName: "Phoebe", lastName: "Mcneil", emailId : "Phoebe.Mcneil@email.com"},
            {firstName: "Tyrone", lastName: "Clements", emailId : "Tyrone.Clements@email.com"},
            {firstName: "Paityn", lastName: "Valenzuela", emailId : "Paityn.Valenzuela@email.com"},
            {firstName: "Zoey", lastName: "Nicholson", emailId : "Zoey.Nicholson@email.com"},
            {firstName: "Nathaniel", lastName: "Huang", emailId : "Nathaniel.Huang@email.com"},
            {firstName: "Dane", lastName: "Marsh", emailId : "Dane.Marsh@email.com"},
            {firstName: "Alma", lastName: "Singh", emailId : "Alma.Singh@email.com"},
            {firstName: "Alex", lastName: "Fitzpatrick", emailId : "Alex.Fitzpatrick@email.com"},
            {firstName: "Kendal", lastName: "Johnston", emailId : "Kendal.Johnston@email.com"},
            {firstName: "Alijah", lastName: "Yoder", emailId : "Alijah.Yoder@email.com"},
            {firstName: "Lyla", lastName: "Bernard", emailId : "Lyla.Bernard@email.com"},
            {firstName: "Marshall", lastName: "Wilkerson", emailId : "Marshall.Wilkerson@email.com"},
            {firstName: "Madalynn", lastName: "Bentley", emailId : "Madalynn.Bentley@email.com"},
            {firstName: "Matilda", lastName: "English", emailId : "Matilda.English@email.com"},
            {firstName: "Cassie", lastName: "Hays", emailId : "Cassie.Hays@email.com"},
            {firstName: "Celia", lastName: "Mckay", emailId : "Celia.Mckay@email.com"},
            {firstName: "Skylar", lastName: "Perez", emailId : "Skylar.Perez@email.com"},
            {firstName: "Tyler", lastName: "Arellano", emailId : "Tyler.Arellano@email.com"},
            {firstName: "Rosemary", lastName: "Beck", emailId : "Rosemary.Beck@email.com"},
            {firstName: "Chaz", lastName: "Black", emailId : "Chaz.Black@email.com"},
            {firstName: "Micaela", lastName: "Norton", emailId : "Micaela.Norton@email.com"},
            {firstName: "Cristal", lastName: "Huff", emailId : "Cristal.Huff@email.com"},
            {firstName: "Davis", lastName: "Hensley", emailId : "Davis.Hensley@email.com"},
            {firstName: "Mia", lastName: "Hull", emailId : "Mia.Hull@email.com"},
            {firstName: "Annabelle", lastName: "Norris", emailId : "Annabelle.Norris@email.com"},
            {firstName: "Rachel", lastName: "Wright", emailId : "Rachel.Wright@email.com"},
            {firstName: "Luis", lastName: "Clark", emailId : "Luis.Clark@email.com"},
            {firstName: "Braylen", lastName: "Meadows", emailId : "Braylen.Meadows@email.com"},
            {firstName: "Paityn", lastName: "Stevens", emailId : "Paityn.Stevens@email.com"},
            {firstName: "Amaya", lastName: "Humphrey", emailId : "Amaya.Humphrey@email.com"},
            {firstName: "Micah", lastName: "Bullock", emailId : "Micah.Bullock@email.com"},
            {firstName: "Valery", lastName: "Mcgrath", emailId : "Valery.Mcgrath@email.com"},
            {firstName: "Courtney", lastName: "Moses", emailId : "Courtney.Moses@email.com"},
            {firstName: "Ezequiel", lastName: "Meyers", emailId : "Ezequiel.Meyers@email.com"},
            {firstName: "Skyler", lastName: "Waller", emailId : "Skyler.Waller@email.com"}
        ]
    },
]


